version: '3.8'
services:
  devopy-ubuntu:
    image: ubuntu:latest
    volumes:
      - .:/workspace
    working_dir: /workspace
    environment:
      - PYTHONUNBUFFERED=1
    command: bash -c "apt-get update && apt-get install -y python3 python3-pip git && pip3 install . && pip3 install pytest && pytest tests/"

  devopy-fedora:
    image: fedora:latest
    volumes:
      - .:/workspace
    working_dir: /workspace
    environment:
      - PYTHONUNBUFFERED=1
    command: bash -c "dnf install -y python3 python3-pip git && pip3 install . && pip3 install pytest && pytest tests/"
