source "https://rubygems.org"

# Use GitHub Pages - to jest jedyny gem, który potrzebujemy
gem "github-pages", ">= 228", group: :jekyll_plugins

# Lock jekyll-sass-converter to 2.x on Linux/macOS
gem "jekyll-sass-converter", "~> 2.0"
