name: Jekyll Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Ensure latest report exists
        run: |
          chmod +x ./ensure_latest_report.sh
          ./ensure_latest_report.sh
      
      - name: Build Jekyll site
        uses: actions/jekyll-build-pages@v1
        with:
          source: .
          destination: ./_site
          future: false
          verbose: true
